# Generated by Django 5.1.2 on 2024-10-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
